[target.x86_64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libssl-dev pkg-config curl unzip libprotobuf-dev",
    "curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.19.4/protoc-3.19.4-linux-x86_64.zip",
    "unzip protoc-3.19.4-linux-x86_64.zip -d /usr",
    "chmod 755 /usr/bin/protoc"
]